# Generated by Django 4.2.11 on 2024-04-13 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('Employee_name', models.CharField(max_length=30, verbose_name='Name')),
                ('Employee_department', models.CharField(choices=[('Product_Adder', 'Product_Adder'), ('Product_Seller', 'Product_Seller'), ('Customer_Adder', 'Customer_Adder')], max_length=20, verbose_name='Department')),
                ('Employee_username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('Employee_Joining_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Join')),
                ('Employee_update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Account Updated')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=30, verbose_name='Name')),
                ('Customer_mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobile Number')),
                ('Customer_email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('Customer_address', models.TextField(max_length=100, verbose_name='Address')),
                ('Customer_Joining_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Join')),
                ('Customer_update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Account Updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=30, verbose_name='Name')),
                ('Product_description', models.TextField(max_length=100, verbose_name='Description')),
                ('Product_quantity', models.CharField(help_text='Quantity like 1kg, 1.5lit, 200g. if no weight leave it blank', max_length=10, verbose_name='Quantity')),
                ('Product_count', models.IntegerField(verbose_name='Count')),
                ('Product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per quantity/count in Rs.')),
                ('Product_image', models.ImageField(null=True, upload_to='product_images')),
                ('Product_add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Add')),
                ('Product_update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of Update')),
                ('maximum_sale', models.IntegerField(default=0, verbose_name='Maximum sale')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobile Number')),
                ('Employee_email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('Employee_address', models.TextField(max_length=200, verbose_name='Address')),
                ('Employee_image', models.ImageField(null=True, upload_to='Employees_images', verbose_name='Image')),
                ('Employee_profile_Joining_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Of Join')),
                ('Employee_profile_update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Account Updated')),
                ('maximum_sale', models.IntegerField(default=0, verbose_name='Maximum sale')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('Employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee_id')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField(verbose_name='Count')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Sell_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Of sell')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='on_counter_billing_app.customer', verbose_name='Customer_id')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee_id')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='on_counter_billing_app.product', verbose_name='Product_id')),
            ],
        ),
    ]
